# SPDX-License-Identifier: GPL-2.0
ccflags-y := -I$(srctree)/$(src)/../include

obj-$(CONFIG_RESCTRL)		+= resctrlfs.o
obj-$(CONFIG_MPAM)  += mpam_resctrl.o mpam_mon.o \
					mpam_ctrlmon.o mpam_device.o mpam_setup.o


