# SPDX-License-Identifier: GPL-2.0 OR BSD-2-Clause
obj-$(CONFIG_INFINIBAND_ERDMA) += erdma.o

erdma-y :=\
			erdma_ae.o erdma_cm.o erdma_common.o erdma_command.o \
			erdma_debug.o erdma_ioctl.o erdma_main.o erdma_obj.o \
			erdma_qp.o erdma_verbs.o
